name         'Nginx'
summary      'Nginx Module'
description  'This is the Nginx Module'
version      '0.0.1'
author       'wileyj'
license      'Apache 2.0'
source       'https://github.com/wileyj/public-puppet/code/modules/local/nginx'
project_page 'https://github.com/wileyj/public-puppet/code/modules/local/nginx'

