class uchiwa::params{
    $files                  = hiera('uchiwa::files', {})
    $users                  = hiera('uchiwa::users',{})
    $classes                = hiera('uchiwa::classes', [])
    $sudo                   = hiera('uchiwa::sudo::conf', {})
    $cron                   = hiera('uchiwa::cron::job', {})
    $packages               = hiera('uchiwa::packages',[])
    $services               = hiera('uchiwa::services',[])
    $sensu_user             = hiera('sensu::users',{})
    $sensu_group            = hiera('sensu::groups',{})
    $sensu_host             = hiera('sensu::host')
    $api_port               = hiera('sensu::api::port')
    $api_user               = hiera('sensu::api::user')
    $api_password           = hiera('sensu::api::password')
    $sensu_use_ssl          = hiera('uchiwa::app::use_ssl')
    $sensu_path             = hiera('uchiwa::app::path')
    $sensu_timeout          = hiera('uchiwa::app::timeout')
    $uchiwa_port            = hiera('uchiwa::app::port')
    $uchiwa_stats           = hiera('uchiwa::app::stats')
    $uchiwa_refresh         = hiera('uchiwa::app::refresh')
    $uchiwa_script_dir      = hiera('uchiwa::script_dir')
    $golang_modules         = hiera('uchiwa::golang::modules',[])

    $uchiwa_admin_user      = hiera('uchiwa::app::admin_user')
    $uchiwa_admin_password  = hiera('uchiwa::app::admin_password')
    $uchiwa_app_users       = hiera('uchiwa::app::users',{})
    $uchiwa_app_datacenters = hiera('uchiwa::app::datacenters',{})

    # host specific config
    $host_files             = hiera('host::files', {})
    $host_sudo              = hiera('host::sudo::conf', {})
    $host_cron              = hiera('host::cron::job', {})
    $host_users             = hiera('host::users', {})
    $host_groups            = hiera('host::groups', {})
    $host_sysctl            = hiera('host::sysctl', {})
    $host_packages          = hiera('host::packages',[])
    $host_python_modules    = hiera('host::python_modules',[])
    $host_nodejs_modules    = hiera('host::nodejs_modules',[])
    $host_golang_modules    = hiera('host::golang_modules',[])
    $host_services          = hiera('host::services',[])
    $host_iptables          = hiera('host::iptables', {})
    $host_keys              = hiera('host::keys',{})
}