name         'Bastion'
summary      'Bastion Module'
description  'This is the Bastion Module'
version      '0.0.1'
author       'wileyj'
license      'Apache 2.0'
source       'https://github.com/wileyj/public-puppet/code/modules/local/bastion'
project_page 'https://github.com/wileyj/public-puppet/code/modules/local/bastion'

