#!/bin/bash

# chkconfig: 345 87 87
# description: transfer-logs

### BEGIN INIT INFO
# Provides:       transfer-logs
# Required-Start: $remote_fs $network
# Required-Stop:  $remote_fs $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    transfer-logs
### END INIT INFO
#


# Source function library.
. /etc/rc.d/init.d/functions
LOG="/var/log/transfer.log"
set -e
export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
OP=$1
APP="/var/log/tomcat8/app"
RETVAL=0
DATE=`date +%m-%d-%y-%H-%M`
HOST=`hostname`
LOCKFILE="/var/lock/subsys/transfer-logs"
S3="s3://local-logs-prod/"
RANDOM=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
ENV=`/usr/bin/facter -p tag_environment`


stop() {
    echo "" > $LOG
    echo "********************************" >> $LOG
    echo `date` >> /var/log/transfer.log
    echo "Environment: $ENV" >> $LOG
    echo -n $"Shutting down $0 "
    if [ -d "$APP" ]; then
        for file in `ls $APP`; do  
            echo "checking $APP/$file" >> $LOG
            SIZE=`wc -c $APP/$file | cut -f1 -d " "`
            echo "$APP/$file SIZE: $SIZE" >> $LOG
            if [ $SIZE -gt 0 ]; then
                NEWFILE=""
                if [[ $file =~ \.gz$ ]]; then
                    echo "Found gz file, copying to S3: aws s3 cp $APP/$file $S3" >> $LOG
                    aws s3 cp $APP/$file $S3
                    if [ $? -eq "0" ];then
                        rm -f $APP/$file
                    fi
                else
                    PREFIX=`echo $file | cut -d "." -f1`
                    SUFFIX=`echo $file | cut -d "." -f2`
                    echo "PREFIX: $PREFIX" >> $LOG
                    echo "SUFFIX: $SUFFIX" >> $LOG
                    if [ $SUFFIX == "log" ]; then
                        echo "FOUND 'log' suffix" >> $LOG
                        NEWFILE="$APP/$PREFIX.$DATE.$HOST.log"
                    else
                        NEWFILE="$APP/$PREFIX.$SUFFIX.$DATE.$HOST.log"
                    fi
                    echo "Moving file: mv $APP/$file $NEWFILE" >> $LOG
                    mv $APP/$file $NEWFILE
                    gzip $NEWFILE
                    echo "Copying to s3: aws s3 cp ${NEWFILE}.gz $S3"  >> $LOG
                    aws s3 cp ${NEWFILE}.gz $S3
                    if [ $? -eq "0" ];then
                        rm -f ${NEWFILE}.gz
                    fi
                fi
            fi
        done
    fi
    return 0
}

if [ $ENV == "production" ];then
    case "$OP" in
        start)
            if [ ! -f "$LOCKFILE" ]
            then
                /bin/touch $LOCKFILE
            fi
            echo -n $"Starting $0 "
            RETVAL=0
        ;;
        status)
            if [ ! -f "$LOCKFILE" ]
            then
                /bin/touch $LOCKFILE
            fi
            echo -n $"Status $0 "
            RETVAL=0
        ;;
        stop)
            if [ -f "$LOCKFILE" ]
            then
                /bin/rm -f $LOCKFILE
            fi
            stop
        ;;
        *)
            stop
    esac
fi
exit $RETVAL
