name         'Beanstalk'
summary      'Beanstalk Module'
description  'This is the Beanstalk Module'
version      '0.0.1'
author       'wileyj'
license      'Apache 2.0'
source       'https://github.com/wileyj/public-puppet/code/modules/local/beanstalk'
project_page 'https://github.com/wileyj/public-puppet/code/modules/local/beanstalk'

