name 'wirbelsturm-supervisor'
version '1.0.3'
source 'https://github.com/miguno/puppet-supervisor.git'
author 'Michael G. Noll, who forked from mhahn, who forked from plathrop'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring supervisord'
description 'Module for managing and configuring supervisord'
project_page 'https://github.com/miguno/puppet-supervisor'
#DISABLED SO WE DO NOT DEPEND ON PUPPETFORGE#dependency 'puppetlabs/stdlib', '>= 4.1.0'
