name         'Puppet'
summary      'Puppet Module'
description  'This is the Puppet Module'
version      '0.0.1'
author       'wileyj'
license      'Apache 2.0'
source       'https://github.com/wileyj/public-puppet/code/modules/local/puppet'
project_page 'https://github.com/wileyj/public-puppet/code/modules/local/puppet'

