class postgres::params{
    $version                      = hiera('postgres::version')
    $short_version                = hiera('postgres::short_version')
    $files                        = hiera('postgres::files', {})
    $postgres_iptables            = hiera('postgres::firewall::rules', {})
    $services                     = hiera('postgres::services',[])
    $packages                     = hiera('postgres::packages',[])
    $users                        = hiera('postgres::users',{})
    $groups                       = hiera('postgres::groups',{})
    $default_statistics_target    = hiera('postgres::conf::default_statistics_target')
    $maintenance_work_mem         = hiera('postgres::conf::maintenance_work_mem')
    $checkpoint_completion_target = hiera('postgres::conf::checkpoint_completion_target')
    $effective_cache_size         = hiera('postgres::conf::effective_cache_size')
    $work_mem                     = hiera('postgres::conf::work_mem')
    $wal_buffers                  = hiera('postgres::conf::wal_buffers')
    $checkpoint_segments          = hiera('postgres::conf::checkpoint_segments')
    $shared_buffers               = hiera('postgres::conf::shared_buffers')
    $max_connections              = hiera('postgres::conf::max_connections')
    $admin                        = hiera('postgres::external::admin',[])
    $slots_ro                     = hiera('postgres::external::slots_ro',[])
    $slots_rw                     = hiera('postgres::external::slots_rw',[])

    # host specific config
    $host_files                   = hiera('host::files', {})
    $host_sudo                    = hiera('host::sudo::conf', {})
    $host_cron                    = hiera('host::cron::job', {})
    $host_users                   = hiera('host::users', {})
    $host_groups                  = hiera('host::groups', {})
    $host_sysctl                  = hiera('host::sysctl', {})
    $host_packages                = hiera('host::packages',[])
    $host_python_modules          = hiera('host::python_modules',[])
    $host_nodejs_modules          = hiera('host::nodejs_modules',[])
    $host_golang_modules          = hiera('host::golang_modules',[])
    $host_services                = hiera('host::services',[])
    $host_iptables                = hiera('host::iptables', {})
    $host_keys                    = hiera('host::keys',{})
}
