class redis::config (
    $port                        = hiera('redis::config::port'),
    $listen                      = hiera('redis::config::listen'),
    $timeout                     = hiera('redis::config::timeout'),
    $redis_loglevel              = hiera('redis::config::loglevel'),
    $logfile                     = hiera('redis::config::logfile'),
    $databases                   = hiera('redis::config::databases'),
    $tcp_backlog                 = hiera('redis::config::tcp_backlog'),
    $save1                       = hiera('redis::config::save_one'),
    $save2                       = hiera('redis::config::save_two'),
    $save3                       = hiera('redis::config::save_three'),
    $rdbcompression              = hiera('redis::config::rdbcompression'),
    $dbfilename                  = hiera('redis::config::dbfilename'),
    $rdb_dir                     = hiera('redis::config::rdb_dir'),
    $masterip                    = hiera('redis::config::masterip'),
    $masterport                  = hiera('redis::config::masterport'),
    $masterauth                  = hiera('redis::config::masterauth'),
    $slave_serve_stale_data      = hiera('redis::config::slave_serve_stale_data'),
    $repl_ping_slave_period      = hiera('redis::config::repl_ping_slave_period'),
    $repl_timeout                = hiera('redis::config::repl_timeout'),
    $requirepass                 = hiera('redis::config::requirepass'),
    $command_config              = hiera('redis::config::command_config'),
    $command_flushall            = hiera('redis::config::command_flushall'),
    $command_flushdb             = hiera('redis::config::command_flushdb'),
    $maxclients                  = hiera('redis::config::maxclients'),
    $maxmemory                   = hiera('redis::config::maxmemory'),
    $maxmemory_policy            = hiera('redis::config::maxmemory_policy'),
    $appendonly                  = hiera('redis::config::appendonly'),
    $appendfsync                 = hiera('redis::config::appendfsync'),
    $no_appendfsync_on_rewrite   = hiera('redis::config::no_appendfsync_on_rewrite'),
    $auto_aof_rewrite_percentage = hiera('redis::config::auto_aof_rewrite_percentage'),
    $auto_aof_rewrite_min_size   = hiera('redis::config::auto_aof_rewrite_min_size'),
    $slowlog_log_slower_than     = hiera('redis::config::slowlog_log_slower_than'),
    $slowlog_max_len             = hiera('redis::config::slowlog_max_len'),
    $list_max_ziplist_entries    = hiera('redis::config::list_max_ziplist_entries'),
    $list_max_ziplist_value      = hiera('redis::config::list_max_ziplist_value'),
    $set_max_intset_entries      = hiera('redis::config::set_max_intset_entries'),
    $zset_max_ziplist_entries    = hiera('redis::config::zset_max_ziplist_entries'),
    $zset_max_ziplist_value      = hiera('redis::config::zset_max_ziplist_value'),
    $activerehashing             = hiera('redis::config::activerehashing'),
) {
    file { 
        '/etc/redis.conf':
            ensure  => file,
            owner   => 'redis',
            group   => 'redis',
            mode    => '0444',
            content => template('redis/redis.conf.erb'),
            notify  => Service["redis"]
    }
}