---
language: ruby
rvm:
  - 2.0.0
env:
  - PUPPET_VERSION="3.2.4"
  - PUPPET_VERSION="3.3.2"
  - PUPPET_VERSION="3.4.3"
  - PUPPET_VERSION="3.5.1"
  - PUPPET_VERSION="3.6.2"
  - PUPPET_VERSION="3.7.4"
sudo: false
bundler_args: --without development
script: bundle exec rake spec SPEC_OPTS='--format documentation' PARSER='future'
notifications:
  email:
    - justin@downing.us
