name         'Roles'
summary      'Roles Module'
description  'This is the Roles Module'
version      '0.0.1'
author       'wileyj'
license      'Apache 2.0'
source       'https://github.com/wileyj/public-puppet/code/modules/local/roles'
project_page 'https://github.com/wileyj/public-puppet/code/modules/local/roles'

