name         'Sumo'
summary      'Sumo Module'
description  'This is the Sumo Module'
version      '0.0.1'
author       'wileyj'
license      'Apache 2.0'
source       'https://github.com/wileyj/public-puppet/code/modules/local/sumo'
project_page 'https://github.com/wileyj/public-puppet/code/modules/local/sumo'

