name         'Jenkins'
summary      'Jenkins Module'
description  'This is the Jenkins Module'
version      '0.0.1'
author       'wileyj'
license      'Apache 2.0'
source       'https://github.com/wileyj/public-puppet/code/modules/local/jenkins'
project_page 'https://github.com/wileyj/public-puppet/code/modules/local/jenkins'

