name         'Grafana'
summary      'Grafana Module'
description  'This is the Grafana Module'
version      '0.0.1'
author       'wileyj'
license      'Apache 2.0'
source       'https://github.com/wileyj/public-puppet/code/modules/local/grafana'
project_page 'https://github.com/wileyj/public-puppet/code/modules/local/grafana'

