name         'Sensu'
summary      'Sensu Module'
description  'This is the Sensu Module'
version      '0.0.1'
author       'wileyj'
license      'Apache 2.0'
source       'https://github.com/wileyj/public-puppet/code/modules/local/sensu'
project_page 'https://github.com/wileyj/public-puppet/code/modules/local/sensu'

