name         'NAT'
summary      'NAT Module'
description  'This is the NAT Module'
version      '0.0.1'
author       'wileyj'
license      'Apache 2.0'
source       'https://github.com/wileyj/public-puppet/code/modules/local/nat'
project_page 'https://github.com/wileyj/public-puppet/code/modules/local/nat'

