#!/bin/bash

SVN_URL="svn+ssh://jenkins@svn.local.com/repos/ops/RPMS"
SRC=$1
DST=/tmp
SHORT=`basename $1|perl -p -i -e 's/-\d+.*//g'`
echo "Making: $DST/$SHORT/{SRPMS,SPECS,BUILD,SOURCES}................"
mkdir -p $DST/$SHORT/{SPECS,BUILD,SOURCES}
CUR=`pwd`
cd $DST/$SHORT
/usr/bin/svn --no-auth-cache co $SVN_URL/$SHORT/SRPMS
echo "Extracting src.rpm contents......."
rpm2cpio $SRC | cpio -i -d -m -v 
find . -maxdepth 1 -type f -name *.spec -exec mv {} SPECS/$SHORT.spec \;
find . -maxdepth 1 -type f -exec mv {} SOURCES/ \;
/usr/bin/svn --no-auth-cache import $SVN_URL/$SHORT -m "adding ${SHORT}"
cd $CUR
