---
puppet::env::modulepath:
    - '$codedir/environments/staging/modules/public:'
    - '$codedir/environments/staging/modules/local'
puppet::env::manifest: '$codedir/environments/staging/manifests/site.pp'
puppet::env::version: '/usr/bin/git --git-dir /etc/puppetlabs/.git rev-parse HEAD'
python::env::name: python27
python::env::version: python2.7
ruby::env::version: ruby-2.2.2 