#!/bin/sh
#!/bin/sh
export PIP_DISABLE_PIP_VERSION_CHECK=1
export GOPATH="/usr/lib/golang/"
export FACTERLIB="/etc/puppetlabs/facter/facts.d"
GITREPO="git@github.com:repo/puppet.git"
if [ -f "/usr/local/bin/pip" ];then
    /usr/local/bin/pip install --upgrade boto
elif [ -f "/usr/bin/pip-2.7" ]; then
    /usr/bin/pip-2.7 install --upgrade boto
else
    /usr/bin/pip install --upgrade boto
fi    
HOST=`/bin/hostname`
#ENV=`/usr/bin/facter -p tag_environment`
ENV="production" # for now, this is it
MANIFESTS="/etc/puppetlabs"
PROGDIR="/opt/puppetlabs"
SITE_PP="${MANIFESTS}/code/environments/${ENV}/manifests/site.pp"
SCRIPT="/opt/scripts/git.sh"
KEY="/root/.ssh/puppet"
LOGFILE="/var/log/puppet/puppet.log"
PROG="${PROGDIR}/bin/puppet"
BINPATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin"
#define puppet variables
puppet_base="/etc/puppetlabs"
puppet_modulepath="$puppet_base/code/modules"
puppet_manifests="$puppet_base/code/environments/production/manifests"
puppet_sitepp="$puppet_manifests/site.pp"

REGION=`curl -s http://169.254.169.254/latest/dynamic/instance-identity/document |grep region | awk -F\" '{print $4}'`
if [ ! -d /opt/scripts ]; then
    echo "Creating dir /opt/scripts"
    mkdir /opt/scripts/
fi

if [ ! -f /opt/scripts/git.sh ]; then
cat <<EOF> /opt/scripts/git.sh
#!/bin/bash
# The MIT License (MIT)
# Copyright (c) 2013 Alvin Abad
 
if [ \$# -eq 0 ]; then
    echo "Git wrapper script that can specify an ssh-key file
Usage:
    git.sh -i ssh-key-file git-command
    "
    exit 1
fi
 
# remove temporary file on exit
trap 'rm -f /tmp/.git_ssh.\$\$' 0
 
if [ "\$1" = "-i" ]; then
    SSH_KEY=\$2; shift; shift
    echo "ssh -i \$SSH_KEY \\\$@" > /tmp/.git_ssh.\$\$
    chmod +x /tmp/.git_ssh.\$\$
    export GIT_SSH=/tmp/.git_ssh.\$\$
fi
 
# in case the git command is repeated
[ "\$1" = "git" ] && shift
 
# Run the git command
git "\$@"
EOF
fi

if [ ! -f /etc/yum.repos.d/local_x86_64.repo ]; then
cat <<EOF> /etc/yum.repos.d/local_x86_64.repo
[local_x86_64]
name=local_x86-64
baseurl=http://s3.amazonaws.com/netflix-yumrepo/x86_64
gpgcheck=0
priority=1
exclude=perl-ExtUtils-MakeMaker* perl-TermReadKey* db4* tkinter27* python27-pip python27-tools python27-setuptools perl-threads*
enabled=1
failovermethod=priority
EOF
fi

if [ ! -f /etc/yum.repos.d/local_noarch.repo ]; then
cat <<EOF> /etc/yum.repos.d/local_noarch.repo
[local_noarch]
name=local_noarch
baseurl=http://s3.amazonaws.com/netflix-yumrepo/noarch
gpgcheck=0
priority=1
exclude=perl-ExtUtils-MakeMaker* perl-TermReadKey* db4* tkinter27* python27-pip python27-tools python27-setuptools perl-threads*
enabled=1
failovermethod=priority
EOF
fi

if [ ! -d /root/.ssh ]; then
    echo "Creating dir /root/.ssh"
    mkdir /root/.ssh
    chmod 700 /root/.ssh
fi

cat <<EOF> /root/.ssh/puppet
-----BEGIN RSA PRIVATE KEY-----
<puppet key>
-----END RSA PRIVATE KEY-----
EOF
chmod 600 /root/.ssh/puppet
chmod 755 /opt/scripts/git.sh
chmod 644 /root/.ssh/known_hosts
chown -R root:root /root/.ssh

if [ ! -d /home/ec2-user/.ssh ];then
    echo "Creating dir /home/ec2-user/.ssh"
    mkdir /home/ec2-user/.ssh
    chmod 700 /home/ec2-user/.ssh
fi

GIT=`rpm -qa | grep "git-" | cut -f3 -d"."`
RUBY=`rpm -qa | grep ruby-[0-9] | cut -f4 -d"."`

if [ $GIT != "local" ]; then
    echo "remove git"
    yum remove -y git
fi

if [ $RUBY != "local" ]; then
    echo "remove ruby"
    yum remove -y ruby*
fi
yum install -y yum-plugin-priorities 
yum remove -y python27-virtualenv
yum install -y \
    git \
    puppet \
    hiera \
    facter \
    augeas \
    augeas-libs \
    ruby \
    ruby-shadow \
    ruby-libs \
    rubygems \
    rubygem-bigdecimal \
    rubygem-psych \
    rubygem-deep_merge \
    rubygem-sys-proctable \
    rubygem-test-unit \
    rubygem-json_pure \
    rubygem-rgen \
    telnet \
    python27 \
    python27-pip \
    sumologic-conf
yum update -y
cat <<EOF> /etc/sumo.conf
name=<name>
accessid=<access id>
accesskey=<access key>
syncSources=/etc/sumo.d/
EOF

if [ ! -d /usr/local/aws -o ! -f /usr/local/bin/aws ]; then
    cd /tmp; curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
    unzip -u awscli-bundle.zip; /tmp/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
    rm -rf /tmp/awscli-bundle*
fi

if [ ! -d "/opt/scripts" ]; then
    mkdir -p /opt/scripts
fi

if [ ! -d "/u" ]; then
    mkdir /u
fi

if [ ! -f "/usr/bin/pip" ]; then
    ln -s /usr/bin/pip-2.7 /usr/bin/pip
fi

pip list \| grep --quiet boto
if [ $? != 0 ]; then
    pip install boto botocore
fi

s_region=`hostname| cut -f3 -d"."`
s_domain=`hostname| cut -f4 -d"."`
s_suffix="com"
s_string="${s_region}.${s_domain}.${s_suffix}"
if grep --quiet $s_string /etc/resolv.conf; then
    echo "resolv.conf entry exists"
else
    echo "resolv.conf entry doesn't exist"
    sed -i -e "s/search ec2.internal/search ec2.internal\nsearch ${s_string}/g" /etc/resolv.conf
fi

if grep --quiet "HOSTNAME=localhost.localdomain" /etc/sysconfig/network; then
    echo "sysconfig/network entry exists"
else
    echo "sysconfig/network entry doesn't exist"
    sed -i -e "s/HOSTNAME=localhost.localdomain/HOSTNAME=`hostname`/g" /etc/sysconfig/network
fi
mkdir -p /etc/puppetlabs/puppet/
mkdir -p /etc/puppetlabs/code/environments/production

cat <<EOF> /etc/puppetlabs/puppet/puppet.conf
[main]
    codedir         = /etc/puppetlabs/code
    confdir         = \$codedir/hieradata
    environment     = production
    basemodulepath  = \$codedir/environments/production/modules/public:\$codedir/environments/production/modules/local    
    factpath        = /etc/puppetlabs/facter/facts.d
    vardir          = /var/lib/puppet
    logdir          = /var/log/puppet
    rundir          = /var/run/puppet
    lastrunfile     = $vardir/state/last_run_summary.yaml { mode=0664 }
    statefile       = $vardir/state/state.yaml { mode=0664 }
    listen          = false
    summarize       = true
    paramcheck      = true
    report          = false
    pluginsync      = false
    pluginsignore   = .svn CVS .hg .git
EOF

if [ ! -d $puppet_base/.git ]; then
    /opt/scripts/git.sh -i /root/.ssh/puppet clone --hard $GITREPO /tmp/puppet-clone
    mv /tmp/puppet-clone/.git $puppet_base/.git
    rm -rf /tmp/puppet-clone
fi
${SCRIPT} -i ${KEY} -C ${MANIFESTS} reset --hard ${REPO}
${SCRIPT} -i ${KEY} -C ${MANIFESTS} clean -f -d
${SCRIPT} -i ${KEY} -C ${MANIFESTS} pull origin ${REPO}
${SCRIPT} -i ${KEY} -C ${MANIFESTS} submodule init
${SCRIPT} -i ${KEY} -C ${MANIFESTS} submodule update
chown -R puppet:puppet /etc/puppetlabs /opt/puppetlabs

if [ -f $puppet_base/scripts/run-puppet-local ]; then
    sh $puppet_base/scripts/run-puppet-local
fi

if [ $? -eq "0" ]
then
    echo "1" > /etc/sysconfig/one-time-init
fi

if [ -f /etc/cron.d/puppet.cron ];then
    rm -rf /etc/cron.d/puppet.cron
fi 
${SCRIPT} -i ${KEY} -C ${MANIFESTS} reset --hard ${REPO}
${SCRIPT} -i ${KEY} -C ${MANIFESTS} clean -f -d
${SCRIPT} -i ${KEY} -C ${MANIFESTS} pull origin ${REPO}
${SCRIPT} -i ${KEY} -C ${MANIFESTS} submodule init
${SCRIPT} -i ${KEY} -C ${MANIFESTS} submodule update
chown -R puppet:puppet /etc/puppetlabs /opt/puppetlabs
sed -i -e '/common\/cron/ s|^#*|#|' /etc/puppetlabs/code/hiera.yaml
/opt/puppetlabs/bin/puppet apply -dv /etc/puppetlabs/code/environments/production/manifests/site.pp | tee /var/log/puppet/puppet.log

hostname localhost
passwd -l root
passwd -l ec2-user
/etc/init.d/collector stop
/etc/init.d/sensu-client stop
if [ -f "/etc/init.d/tomcat8" ];then
    chown -R tomcat:tomcat /var/log/tomcat* /etc/tomcat* /usr/share/tomcat*
    /etc/init.d/tomcat8 stop
fi
if [ -f "/etc/init.d/httpd" ];then
    /etc/init.d/httpd stop
fi

# remove stuff we don't want on new host
rm -rf /var/log/*.gz /var/log/*.old /var/log/sensu/* /varlog/httpd/* /var/log/tomcat8/* /etc/sensu/conf.d/client.json /etc/init.d/sensu-* /var/log/firstboot* /var/tmp/instance* /var/lib/tomcat8/webapps/* /etc/sysconfig/tomcat8
if [ -f "/var/lock/subsys/transfer-logs" ]
then
    rm -rf /var/lock/subsys/transfer-logs 
fi

# clean logs
for i in `ls /var/log` ; do 
    if [ -f "/var/log/$i" ]; then 
        shred /var/log/$i && echo > /var/log/$i
    fi
done

find /root/.*history /home/*/.*history -exec rm -f {} \;
sed -i -e '/^#.*15/s/^#//' /etc/cron.d/puppet.cron
/opt/scripts/git.sh -i /root/.ssh/puppet -C /etc/puppetlabs reset --hard origin/HEAD
/opt/scripts/git.sh -i /root/.ssh/puppet -C /etc/puppetlabs clean -f -d
/opt/scripts/git.sh -i /root/.ssh/puppet -C /etc/puppetlabs pull origin
/opt/scripts/git.sh -i /root/.ssh/puppet -C /etc/puppetlabs submodule init
/opt/scripts/git.sh -i /root/.ssh/puppet -C /etc/puppetlabs submodule update
chown -R puppet:puppet /etc/puppetlabs /opt/puppetlabs
echo "*/15 * * * *  root sh /etc/puppetlabs/scripts/run-puppet > /dev/null 2>&1" > /etc/cron.d/puppet.cron
sleep 20
init 0
