name         'Uchiwa'
summary      'Uchiwa Module'
description  'This is the Uchiwa Module'
version      '0.0.1'
author       'wileyj'
license      'Apache 2.0'
source       'https://github.com/wileyj/public-puppet/code/modules/local/uchiwa'
project_page 'https://github.com/wileyj/public-puppet/code/modules/local/uchiwa'

