name         'SSH'
summary      'SSH Module'
description  'This is the SSH Module'
version      '0.0.1'
author       'wileyj'
license      'Apache 2.0'
source       'https://github.com/wileyj/public-puppet/code/modules/local/ssh'
project_page 'https://github.com/wileyj/public-puppet/code/modules/local/ssh'

