name         'Tomcat'
summary      'Tomcat Module'
description  'This is the Tomcat Module'
version      '0.0.1'
author       'wileyj'
license      'Apache 2.0'
source       'https://github.com/wileyj/public-puppet/code/modules/local/tomcat'
project_page 'https://github.com/wileyj/public-puppet/code/modules/local/tomcat'

