name         'Graphite'
summary      'Graphite Module'
description  'This is the Graphite Module'
version      '0.0.1'
author       'wileyj'
license      'Apache 2.0'
source       'https://github.com/wileyj/public-puppet/code/modules/local/graphite'
project_page 'https://github.com/wileyj/public-puppet/code/modules/local/graphite'

