name         'Resources'
summary      'Resources Module'
description  'This is the Resources Module'
version      '0.0.1'
author       'wileyj'
license      'Apache 2.0'
source       'https://github.com/wileyj/public-puppet/code/modules/local/resources'
project_page 'https://github.com/wileyj/public-puppet/code/modules/local/resources'

